### ISSUE TITLE
Prevent Height changes based on  testimonial length

### ISSUE THREAD

**Issue by dhawalhshah** [classcentral/review-widget#1]
The height of the review widget changes based on what the testimonials length is. It should be fixed to show 3 lines of text. For longer text it should be truncated with ellipses i.e '...'

**Comment by prakhar1989** [comment]
This should ideally be done at the backend. When a summary is returned from an API it should be trimmed to `n` characters with ellipses added. 

I've added two labels to designate whether an issue pertains to the backend or the widget.
