### ISSUE TITLE
Config parameters and Url

### ISSUE THREAD

**Issue by dhawalhshah** [classcentral/review-widget#2]
In v1 the publisher can pass the following parameters (at least one of them is necessary) :
* course-id - Numerical id assigned by Class Central's system i.e 2406
* course-code - A unique identifier for the course i.e coursera_mmds

These should be passed as GET parameters attached to the base url. The base url will be the same for all courses.

**Comment by prakhar1989** [comment]
Why are both required? Wouldn't `course-id` be enough for you to identify the request on the server-side?

**Comment by dhawalhshah** [comment]
The provider might not know what Class Central's course id is going to be. But they might have a course code which might be the same code that we use on the backend.

**Comment by prakhar1989** [comment]
When the provider generates the code to paste in the page, the generated HTML code will have the `course-id` embedded. Similar to how other widget embed unique identifiers, right?

**Comment by dhawalhshah** [comment]
Thats true if they have only one or few courses. For providers with n courses - they wont be able to generate n widgets. So we will have to use a agreed upon unique identifier that they can pull from their database.

**Comment by prakhar1989** [comment]
FYI, this functionality is already baked in. The `id` parameter refers to the cc course id. Are you looking for anything else?

```HTML
 <div class="classcentral-review" lang="en" data-id="835" data-theme="light"> </div>
 <script async src="/widget.js" charset="utf-8"></script>
```

**Comment by prakhar1989** [comment]
Ok cool. So instead of one `data-id` we'll `data-code` as well? Thats sounds fine.

**Comment by dhawalhshah** [comment]
Yes. `data-code` works

**Comment by prakhar1989** [comment]
Do we still need data-code or will data-id suffice?

**Comment by dhawalhshah** [comment]
We need both. I have added support for both in the backend.

**Comment by prakhar1989** [comment]
Ok. Share a sample URL for me to test and I'll send in a PR in some time.

**Comment by dhawalhshah** [comment]
https://dev.classcentral.io/reviews/widget?course-id=5000

**Comment by prakhar1989** [comment]
I need a one which requires both - `id` and `code`

**Comment by dhawalhshah** [comment]
Its an OR
https://dev.classcentral.io/reviews/widget?course-id=2161
https://dev.classcentral.io/reviews/widget?course-code=coursera_learning

These two are the samepage.
