### ISSUE TITLE
Write a Review button

### ISSUE THREAD

**Issue by dhawalhshah** [classcentral/review-widget#3]
In Version 1, the write a review should just be a simple link that opens up a page in a new tab.

**Comment by prakhar1989** [comment]
Can you provide the link to the page that is to be opened? Will that be parameterized as well?

**Comment by dhawalhshah** [comment]
It will be something like this:
https://www.class-central.com/review/new/766 

This I can generate it in the backend. You could put a placeholder for now.

**Comment by dhawalhshah** [comment]
Fixed in the backend
