### ISSUE TITLE
Generating production assets

### ISSUE THREAD

**Issue by dhawalhshah** [classcentral/review-widget#5]
Some sort of tool chain (grunt, gulp, etc) to generate a production version of widget.js.

**Comment by prakhar1989** [comment]
Have added a `gulpfile` and a default task to minify widget.js. The rest of the assets will be returned from the backend, so I've added comments in the gulpfile for you to add the respective CSS / JS files.

To run 
```
$ npm install
$ gulp
```

PS: I would advise adding LICENSE information in the repo.

**Comment by prakhar1989** [comment]
Just saw that you've already done the needful. Closing this issue.
